# Generated by Django 3.0.5 on 2020-04-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='category',
            field=models.CharField(default='stock', max_length=20),
            preserve_default=False,
        ),
    ]
