# Generated by Django 3.0.5 on 2020-04-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('index', models.CharField(blank=True, max_length=20)),
                ('prevpredict', models.FloatField(blank=True)),
                ('predict', models.FloatField(blank=True)),
            ],
        ),
    ]
