# Generated by Django 3.0.5 on 2020-04-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinfo',
            name='country',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='prevpredict',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
