# Generated by Django 3.0.5 on 2020-04-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_auto_20200424_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinfo',
            name='index',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
